### ISSUE TITLE
Internal Renderer doesn't work on Windows even with ffmpeg

### ISSUE THREAD

**Issue by flleaf** [matcool/TrashBot#12]
![изображение](https://user-images.githubusercontent.com/34797678/144755761-f8bf7f6e-a12e-4cff-833b-40d4872f203c.png)
![20211205225704_1](https://user-images.githubusercontent.com/34797678/144755832-10ff6a19-65e4-449e-be64-b465e8073742.jpg)

**Comment by Riminaru** [comment]
have you tried moving ffmpeg.exe to your Geometry Dash folder? it works for me.

**Comment by flleaf** [comment]
yes, i just confused path with environment variable PATH
