### ISSUE TITLE
practice respawn crashes with echo (v1.4.1)

### ISSUE THREAD

**Issue by Mefistic** [matcool/TrashBot#9]
the title says everything

**Comment by matcool** [comment]
dont use two bots at once duh

**Comment by Mefistic** [comment]
> dont use two bots at once duh

well then make a actual functional bot instead of 0 accuracy shit

**Comment by matcool** [comment]
😥

**Comment by Mefistic** [comment]
ok sorry that was really rude, but please make standalone internal recorder
